"""AI Autoplay Screen — type a natural language prompt, get an intelligent queue."""

from __future__ import annotations

from textual import work
from textual.app import ComposeResult
from textual.containers import Horizontal, Vertical
from textual.screen import ModalScreen
from textual.widgets import Button, Input, Label

from ytmuxiris.utils.logger import get_logger

logger = get_logger(__name__)


class AutoplayScreen(ModalScreen[None]):
    """Modal overlay: user enters a free-text music prompt, AI builds the queue."""

    BINDINGS = [("escape", "dismiss", "Cancel")]

    def compose(self) -> ComposeResult:
        with Vertical(id="autoplay-dialog"):
            yield Label("AI Autoplay", id="autoplay-title", classes="autoplay-title")
            yield Label(
                "Describe the music you want — artist, mood, energy, genre…",
                classes="autoplay-hint",
            )
            yield Input(
                placeholder='e.g. "chill lo-fi for studying" or "like this but more upbeat"',
                id="autoplay-input",
            )
            yield Label("", id="autoplay-status", classes="autoplay-status")
            with Horizontal(id="autoplay-actions"):
                yield Button("Play", id="btn-autoplay", variant="primary")
                yield Button("Cancel", id="btn-cancel")

    def on_mount(self) -> None:
        self.query_one("#autoplay-input", Input).focus()

    # ------------------------------------------------------------------
    # Events
    # ------------------------------------------------------------------

    def on_input_submitted(self, event: Input.Submitted) -> None:
        self._start(event.value)

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "btn-autoplay":
            self._start(self.query_one("#autoplay-input", Input).value)
        elif event.button.id == "btn-cancel":
            self.dismiss()
        event.stop()

    # ------------------------------------------------------------------
    # Autoplay worker
    # ------------------------------------------------------------------

    def _start(self, prompt: str) -> None:
        prompt = prompt.strip()
        if not prompt:
            return
        self.query_one("#btn-autoplay", Button).disabled = True
        self.query_one("#autoplay-input", Input).disabled = True
        self._set_status("Starting…")
        self._run_autoplay(prompt)

    @work(exclusive=True)
    async def _run_autoplay(self, prompt: str) -> None:
        app = self.app  # type: ignore[attr-defined]
        engine = app.autoplay_engine
        queue_manager = app.queue

        engine.update_context(
            current_song=queue_manager.current_song,
            queue_songs=queue_manager.queue,
            history=queue_manager.history,
        )

        try:
            songs = await engine.run(prompt, on_status=self._set_status)
        except Exception as exc:
            logger.error("Autoplay engine error: %s", exc)
            self._set_status(f"Error: {exc}")
            self._re_enable()
            return

        if not songs:
            self._set_status("No songs found — try a different prompt.")
            self._re_enable()
            return

        queue_manager.set_queue(songs)
        await queue_manager.play_now(songs[0])

        # Persist this autoplay session as a YouTube Music playlist so the
        # user can revisit it later from Library → Playlists.
        try:
            await self._save_autoplay_playlist(prompt, songs)
        except Exception as exc:  # noqa: BLE001
            logger.warning("Failed to persist autoplay playlist: %s", exc)

        self.dismiss()

    async def _save_autoplay_playlist(self, prompt: str, songs: list) -> None:
        api = self.app.api  # type: ignore[attr-defined]
        from datetime import datetime

        title = f"Autoplay: {prompt.strip()[:60]}"
        description = (
            f"Generated by ytmuxiris AI on "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M')} from prompt: {prompt.strip()}"
        )
        video_ids = [s.video_id for s in songs if s.video_id]
        if not video_ids:
            return
        pid = await api.create_playlist(title=title, description=description)
        if not pid:
            return
        ok = await api.add_to_playlist(pid, video_ids)
        if ok:
            try:
                self.app.notify(  # type: ignore[attr-defined]
                    f"Saved “{title}” to your YouTube Music playlists.",
                    timeout=3,
                )
            except Exception:
                pass

    # ------------------------------------------------------------------
    # UI helpers
    # ------------------------------------------------------------------

    def _set_status(self, msg: str) -> None:
        try:
            self.query_one("#autoplay-status", Label).update(msg)
        except Exception as exc:
            logger.debug("_set_status: %s", exc)

    def _re_enable(self) -> None:
        try:
            self.query_one("#btn-autoplay", Button).disabled = False
            self.query_one("#autoplay-input", Input).disabled = False
        except Exception as exc:
            logger.debug("_re_enable: %s", exc)
